# Generated by Django 6.0.4

from django.db import migrations

def cleanup_orphaned_users(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    
    orphaned_students = User.objects.filter(is_student=True, student_profile__isnull=True)
    count_students = orphaned_students.count()
    if count_students > 0:
        print(f"\n[Migration] Deleting {count_students} orphaned student user records...")
        orphaned_students.delete()
        
    orphaned_lecturers = User.objects.filter(is_lecturer=True, lecturer_profile__isnull=True)
    count_lecturers = orphaned_lecturers.count()
    if count_lecturers > 0:
        print(f"[Migration] Deleting {count_lecturers} orphaned lecturer user records...")
        orphaned_lecturers.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cleanup_orphaned_users, reverse_code=migrations.RunPython.noop),
    ]
