"""
TOTP Verification Utilities

Verifies the 6-digit TOTP code generated by the Arduino hardware.

How it works:
  1. During enrolment the Arduino generates a 128-bit random secret
     and stores it in its EEPROM. The Base32-encoded form is printed
     to the Serial Monitor and must be pasted into:
       Django Admin → Student Profiles → <student> → totp_secret

  2. When a student marks attendance:
       a. They enter their numeric fingerprint ID on the keypad.
       b. They place their finger on the AS608 sensor.
       c. The Arduino verifies the fingerprint, reads the secret
          from EEPROM, and computes TOTP(secret, unix_time).
       d. The 6-digit OTP is shown on the LCD for 10 seconds.
       e. The student types this code into the web portal.

  3. This function recomputes TOTP server-side with the same secret
     and a ±1 step (30 s) tolerance to cover minor RTC drift.

Test student (seed data):
  fingerprint_id = 999, totp_secret = '' (empty)
  The stub below accepts OTP 482391 for that ID only.
  For all real students the secret must be non-empty (set via Admin).
"""

import pyotp


def verify_otp(fingerprint_id: int, otp_code: str):
    """
    Verify the OTP code for a student identified by fingerprint_id.

    Args:
        fingerprint_id (int): The student's fingerprint slot ID from the Arduino.
        otp_code (str): The 6-digit OTP displayed on the Arduino LCD.

    Returns:
        tuple: (is_valid: bool, error_message: str | None)
    """
    from accounts.models import StudentProfile  # local import avoids circular ref

    # ---------- Locate student ----------
    try:
        student = StudentProfile.objects.get(fingerprint_id=fingerprint_id)
    except StudentProfile.DoesNotExist:
        return False, 'No student found with this fingerprint ID.'

    # ---------- Test stub (seed student, no hardware secret) ----------
    if not student.totp_secret:
        # No secret stored yet — only accept the hardcoded test OTP
        if fingerprint_id == 999 and str(otp_code) == '482391':
            return True, None
        return False, (
            'No TOTP secret found for this student. '
            'Enrol the fingerprint on the Arduino device and paste the '
            'Base32 secret into the student profile via the Admin panel.'
        )

    # ---------- Real TOTP verification ----------
    totp = pyotp.TOTP(student.totp_secret)

    # valid_window=1 accepts the current, previous, and next 30-second step,
    # giving a ±30 s tolerance for DS1302 clock drift.
    if totp.verify(str(otp_code), valid_window=1):
        return True, None

    return False, 'Invalid or expired OTP. Please try again.'
