# Generated by Django 6.0.4 on 2026-04-24 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('100L', '100 Level'), ('200L', '200 Level'), ('300L', '300 Level'), ('400L', '400 Level'), ('500L', '500 Level')], max_length=4)),
                ('department', models.CharField(choices=[('Aeronautical', 'Aeronautical Engineering'), ('Chemical', 'Chemical Engineering'), ('Civil', 'Civil Engineering'), ('Biomedical', 'Biomedical Engineering'), ('Computer', 'Computer Engineering'), ('Electrical', 'Electrical Engineering'), ('Petroleum', 'Petroleum Engineering'), ('Mechanical', 'Mechanical Engineering'), ('Mechatronics', 'Mechatronics Engineering')], max_length=50)),
                ('credits', models.IntegerField(default=3)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LecturerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_assignments', to='courses.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.lecturerprofile')),
            ],
            options={
                'db_table': 'lecturer_assignments',
                'unique_together': {('lecturer', 'course')},
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'student_enrollments',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
