/**
 * Constants used throughout the application.
 */

export const DEPARTMENTS = [
  { value: 'Aeronautical', label: 'Aeronautical Engineering' },
  { value: 'Chemical', label: 'Chemical Engineering' },
  { value: 'Civil', label: 'Civil Engineering' },
  { value: 'Biomedical', label: 'Biomedical Engineering' },
  { value: 'Computer', label: 'Computer Engineering' },
  { value: 'Electrical', label: 'Electrical Engineering' },
  { value: 'Petroleum', label: 'Petroleum Engineering' },
  { value: 'Mechanical', label: 'Mechanical Engineering' },
  { value: 'Mechatronics', label: 'Mechatronics Engineering' },
];

export const LEVELS = [
  { value: '100L', label: '100 Level' },
  { value: '200L', label: '200 Level' },
  { value: '300L', label: '300 Level' },
  { value: '400L', label: '400 Level' },
  { value: '500L', label: '500 Level' },
];

export const TITLES = [
  { value: 'Engr', label: 'Engr' },
  { value: 'Dr', label: 'Dr' },
  { value: 'Prof', label: 'Prof' },
];

export const GRADING_SCALE = [
  { min: 70, max: 100, grade: 'A', gp: 5.0 },
  { min: 60, max: 69, grade: 'B', gp: 4.0 },
  { min: 50, max: 59, grade: 'C', gp: 3.0 },
  { min: 45, max: 49, grade: 'D', gp: 2.0 },
  { min: 0, max: 44, grade: 'F', gp: 0.0 },
];

export const FAQ_ITEMS = [
  {
    question: 'What is TOTP (Time-based One-Time Password)?',
    answer: 'TOTP is a temporary passcode generated by an algorithm that uses the current time as a source of uniqueness. In this system, a shared secret is stored on both the Arduino hardware device and the server. The Arduino device generates a 6-digit code using this secret and the current time from the Real-Time Clock (RTC) module, which the student then enters on the web portal to verify their identity and mark attendance.',
  },
  {
    question: 'How does offline attendance work?',
    answer: 'The attendance system uses a fingerprint sensor connected to an Arduino device with an RTC (Real-Time Clock) module. When a student scans their fingerprint, the device generates a time-based OTP code. The student then enters this code along with their fingerprint ID on the web portal. The server verifies the OTP independently using the same shared secret and time window, ensuring the student was physically present at the device.',
  },
  {
    question: 'What if I forget my fingerprint ID?',
    answer: 'Your fingerprint ID is assigned when you register your fingerprint on the Arduino device. If you have forgotten your ID, please contact your department administrator or the system admin who can look up your fingerprint ID in the system.',
  },
  {
    question: 'Can a lecturer manually mark attendance?',
    answer: 'Yes. Lecturers have the ability to override attendance records. They can change a student\'s status from Absent to Excused (which counts as present for percentage calculations), or manually mark a student as Present if there were technical issues with the device.',
  },
  {
    question: 'How is the attendance percentage calculated?',
    answer: 'Attendance percentage is calculated as (Number of classes attended / Total classes held) x 100. Cancelled class sessions are excluded from the total count. Classes where a student is marked as "Excused" are counted as attended for percentage purposes.',
  },
  {
    question: 'What happens if multiple classes are active at the same time?',
    answer: 'If you are enrolled in multiple courses that have overlapping class sessions, the system will detect this and present you with a list of active classes. You can then select which class you are attending to mark your attendance for that specific session.',
  },
  {
    question: 'How do I view my attendance history?',
    answer: 'After marking your attendance, you will see a button to view your attendance history. You can also navigate to the attendance history page directly and verify your identity using your fingerprint ID and OTP code to view all your past attendance records.',
  },
  {
    question: 'Who manages the courses and class schedules?',
    answer: 'The system administrator manages the master list of courses. Lecturers are assigned to courses either during their registration or by the admin. Lecturers then create and manage class sessions (schedules) for their assigned courses through the lecturer dashboard.',
  },
];

export const PRIVACY_POLICY = `
<h2>Privacy Policy</h2>
<p><strong>Last updated:</strong> April 2026</p>

<h3>1. Information We Collect</h3>
<p>We collect information necessary for the operation of the automated class attendance system, including:</p>
<ul>
  <li><strong>Student Data:</strong> Full name, matriculation number, academic level, department, email address, phone number, and fingerprint ID.</li>
  <li><strong>Lecturer Data:</strong> Name, title, department, email, office phone number, and course assignments.</li>
  <li><strong>Attendance Records:</strong> Timestamps of attendance marking, class session details, and verification logs.</li>
  <li><strong>System Logs:</strong> Action logs for security and audit purposes.</li>
</ul>

<h3>2. How We Use Your Information</h3>
<p>Your information is used solely for the purposes of:</p>
<ul>
  <li>Verifying student identity for attendance marking</li>
  <li>Recording and calculating attendance percentages</li>
  <li>Generating attendance reports and grade calculations</li>
  <li>System administration and security auditing</li>
</ul>

<h3>3. Data Security</h3>
<p>We implement appropriate technical and organizational measures to protect your personal data, including:</p>
<ul>
  <li>Encrypted password storage using industry-standard hashing algorithms</li>
  <li>JWT-based authentication with token expiration</li>
  <li>TOTP-based verification for student attendance (hardware-dependent)</li>
  <li>Access controls based on user roles (student, lecturer, admin)</li>
</ul>

<h3>4. Data Retention</h3>
<p>Attendance records and user data are retained for the duration of the academic program plus any additional period required by university regulations. Students and lecturers can request data review through their department administration.</p>

<h3>5. Third-Party Sharing</h3>
<p>We do not share your personal data with third parties except as required by university policy or applicable law.</p>

<h3>6. Contact</h3>
<p>For questions about this privacy policy or your data, please use the Contact Us form or reach out to the system administrator.</p>
`;
